server:
  port: "8000"
  mode: "debug"

services:
  datacollector: "http://data-collector:8080"
  dataprocessing: "http://data-processing:5000"
  notification: "http://notification:9090"
  anomalydetection: "http://anomaly-detection:6000"


auth:
  jwtsecret: "your-secret-key"
  enabled: false