FROM golang:1.18 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o api-gateway .



COPY --from=builder /app/api-gateway .
COPY --from=builder /app/config.yaml .

EXPOSE 8000

CMD ["./api-gateway"]