version: '3.9'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  #mosquitto MQTT Broker
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSockets port (isteğe bağlı)
    volumes:
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    networks:
      - app-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    
  #influxdb
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - app-network


  # Veri toplama servisi
  data-collector:
    build: ./data-collector
    container_name: data-collector
    ports:
      - "8080:8080"
    environment:
      - .env
    depends_on:
      - rabbitmq
      - mqtt-broker
      - mongodb
    networks:
      - app-network


  # data-Processing
  data-processing:
    build: ./data-processing
    container_name: data-processing
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
      - influxdb
    networks:
      - app-network

    # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - .env
    volumes:
      - ./api-gateway/config.yaml:/root/config.yaml
    depends_on:
      - data-collector
      - data-processing
    networks:
      - app-network

volumes:
  mongodb_data:
  mqtt_data:
  mqtt_log:
  rabbitmq_data:
  influxdb_data:

  # Redis
networks:
  app-network: