FROM node:22-alpine as build

# Çalışma dizini oluştur
WORKDIR /app

# Package.json ve lock dosyasını kopyala
COPY package*.json ./

# Eksik bağımlılıkları kontrol et ve yükle
RUN npm install axios mapbox-gl

# Tüm bağımlılıkları yükle
RUN npm install

# Kaynak kodları kopyala
COPY . .

# Uygulamayı build et
RUN npm run build

# Nginx yükleme
FROM nginx:alpine

# Frontend build çıktısını Nginx'e kopyala
COPY --from=0 /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Port 80'i dinle
EXPOSE 80

# Nginx başlat
CMD ["nginx", "-g", "daemon off;"]