server:
  port: "9090"
  mode: "debug"

mongodb:
  uri: "mongodb://admin:password@mongodb:27017/"
  database: "notification_db"
  collection: "users"

rabbitmq:
  uri: "amqp://admin:password123@rabbitmq:5672/"
  exchange: "pollution.data"
  queue: "anomaly-data"
  routingkey: "anomaly.data"

email:
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  password: "your-email-password"
  from: "your-email@gmail.com"
