server:
  port: "8080"
  mode: "debug"

mongodb:
  uri: "mongodb://admin:password@mongodb:27017/"
  database: "pollution_db"
  collection: "raw_data"

mqtt:
  brokerurl: "mqtt://mqtt-broker:1883"
  clientid: "data-collector"
  topic: "pollution"

rabbitmq:
  uri: "amqp://admin:password123@rabbitmq:5672/"
  exchange: "pollution.data"
  queue: "raw-data"
  routingkey: "raw.data"